name: Build Knipser

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/karstenweikamp/knipser-builder:latest
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: 💾 Cache CMake build directory
      id: cache-build
      uses: actions/cache@v3
      with:
        path: build_${{ matrix.build_type }}
        key: ${{ runner.os }}-docker-cmake-${{ matrix.build_type }}-${{ hashFiles('CMakeLists.txt', '**/*.c', '**/*.h', 'wayland-protocols/*.xml') }}
        restore-keys: |
          ${{ runner.os }}-docker-cmake-${{ matrix.build_type }}-

    - name: 🔄 Configure CMake
      run: |
        mkdir -p build_${{ matrix.build_type }}
        cd build_${{ matrix.build_type }}
        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          ..

    - name: 🚀 Build
      run: |
        cd build_${{ matrix.build_type }}
        ninja

    - name: 📸 Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: knipser-${{ matrix.build_type }}
        path: |
          build_${{ matrix.build_type }}/knipser
          build_${{ matrix.build_type }}/compile_commands.json
        if-no-files-found: error
